twilio: # Twilio gateway configuration
  accountId: ACe53c252e22cb561c107925bd1c98845f
  accountToken: b3c674bfc67e9521cfa4923e30073597
  numbers: # Numbers allocated in Twilio
    - 18782084631 # First number
    # - # Second number
    # - # Third number
    # - # ...
    # - # Nth number
  messagingServicesId: 123456
  localDomain: 127.0.0.1 # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: 1024 # Size of push pending queue

# redphone:
#   authKey: # Deprecated

turn: # TURN server configuration
  secret: test # TURN server secret
  uris:
    - turn:103.218.240.185:4433
    # - stun:yourdomain:80
    # - stun:yourdomain.com:443
    # - turn:yourdomain:443?transport=udp
    # - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: http://127.0.0.1:6379
  replicaUrls: 
    - http://127.0.0.1:6379

directory:
  redis: # Redis server configuration for directory cluster
    url: http://127.0.0.1:6379
    replicaUrls: 
      - http://127.0.0.1:6379
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: ffffff # hex-encoded secret shared with CDS used to generate auth tokens for Signal users
    userAuthenticationTokenUserIdSecret: ffffff # hex-encoded secret shared among Signal-Servers to obscure user phone numbers from CDS
  sqs:
    accessKey: 624364587793      # AWS SQS accessKey
    accessSecret: secretdev  # AWS SQS accessSecret
    queueUrl: https://sqs.ap-southeast-1.amazonaws.com      # AWS SQS queue url
  server:
    replicationUrl: https://sqs.ap-southeast-1.amazonaws.com   # CDS replication endpoint base url
    replicationPassword: ffffff          # CDS replication endpoint password
    replicationCaCertificate: ffffff     # CDS replication endpoint TLS certificate trust root
    # reconciliationChunkSize: 1000      # CDS reconciliation chunk size
    # reconciliationChunkIntervalMs: 1000 # CDS reconciliation chunk interval, in milliseconds

messageCache: # Redis server configuration for message store cache
  redis: 
    url: http://127.0.0.1:6379
    replicaUrls:
      - http://127.0.0.1:6379


pushScheduler: 
  url: http://127.0.0.1:6379
  replicaUrls:
    - http://127.0.0.1:6379

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres123
  url: jdbc:postgresql://localhost:5432/messagedb

abuseDatabase: # Postgresql database configuration for abuse store
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres123
  url: jdbc:postgresql://localhost:5432/abusedb

accountDatabaseCrawler:
  chunkSize: 1000

attachments: # AWS S3 configuration
  accessKey: AKIAIAYIW4BWBR2U7HIA
  accessSecret: ocRCjLRwaG5OBlwywWuRU3PICWqkoy0U9
  bucket: tick-s3

profiles: # AWS S3 configuration
  accessKey: AKIAIAYIW4BWBR2U7HIA
  accessSecret: ocRCjLRwaG5OBlwywWuRU3PICWqkoy0U9
  bucket: tick-s3
  region: ap-southeast-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres123
  url: jdbc:postgresql://localhost:5432/accountdb

unidentifiedDelivery:
  certificate: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMQ
  privateKey: TTEyMzQ1Njc4OU0xMjM0NTY3ODlNMTIzNDU2Nzg5MDE=
  expiresDays: 2

voiceVerification:
  url: http://localhost:6379
  locales:
    - ffffff

apn: # Apple Push Notifications configuration
  bundleId: 123456
  pushCertificate: AKIAIAYIW4BWBR2U7HIA
  pushKey: AKIAIAYIW4BWBR2U7HIA

gcm: # GCM Configuration
  senderId: 123456
  apiKey: AKIAIAYIW4BWBR2U7HIA
